swagger: "2.0"
info:
  title: Code4Teens REST API
  version: 1.0.0
schemes:
  - https
basePath: /v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /auth/login:
    post:
      summary: Log a User in
      operationId: login
      tags:
        - Auth
      x-google-backend:
        address: https://api-auth-gzuvchc2qq-as.a.run.app/auth/login
      parameters:
        - in: body
          name: credentials
          description: Login credentials
          schema:
            type: object
            required:
              - id
              - password
            properties:
              id:
                type: integer
                description: Discord ID
                minimum: 111111111111111111
                maximum: 999999999999999999
              password:
                type: string
                description: Password
            example:
              id: 111111111111111111
              password: password
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              title:
                type: string
              status:
                type: integer
              detail:
                type: integer
            example:
              title: OK
              status: 200
              detail: User 111111111111111111 logged in
        400:
          $ref: '#/responses/400-Bad-Request'
        401:
          description: Unauthorised
          schema:
            type: object
            properties:
              title:
                type: string
              status:
                type: integer
              detail:
                type: integer
            example:
              title: Unauthorised
              status: 401
              detail: Wrong password for User 111111111111111111
        404:
          description: Not Found
          schema:
            type: object
            properties:
              title:
                type: string
              status:
                type: integer
              detail:
                type: integer
            example:
              title: Not Found
              status: 404
              detail: User 111111111111111111 not found
  /subscriptions:
    get:
      summary: Get all Subscriptions
      operationId: get_subscriptions
      tags:
        - Subscription
      x-google-backend:
        address: https://api-subscriptions-gzuvchc2qq-as.a.run.app/subscriptions
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Subscription'
            example:
              - id: 1
                email: john.doe@gmail.com
                created_at: "2021-04-20T08:42:00"
              - id: 2
                email: jane.doe@gmail.com
                created_at: "2021-04-20T08:42:00"
    post:
      summary: Create a Subscription
      operationId: create_subscription
      tags:
        - Subscription
      x-google-backend:
        address: https://api-subscriptions-gzuvchc2qq-as.a.run.app/subscriptions
      parameters:
        - in: body
          name: details
          description: Subscription details
          schema:
            type: object
            required:
              - email
            properties:
              email:
                type: string
                description: Email address
                maxLength: 64
            example:
              email: john.doe@gmail.com
      responses:
        201:
          description: Created
          schema:
            type: object
            properties:
              title:
                type: string
              status:
                type: integer
              detail:
                type: integer
            example:
              title: Created
              status: 201
              detail: Subscription created
        400:
          $ref: '#/responses/400-Bad-Request'
        409:
          description: Conflict
          schema:
            type: object
            properties:
              title:
                type: string
              status:
                type: integer
              detail:
                type: integer
            example:
              title: Conflict
              status: 409
              detail: Subscription already exists
responses:
  400-Bad-Request:
    description: Bad Request
    schema:
      $ref: '#/definitions/400-Bad-Request'
definitions:
  Subscription:
    type: object
    properties:
      id:
        type: integer
      email: 
        type: string
      created_at:
        type: string
    example:
      id: 1
      email: john.doe@gmail.com
      created_at: "2021-04-20T08:42:00"
  400-Bad-Request:
    type: object
    properties:
      title:
        type: string
      status:
        type: integer
      detail:
        type: integer
    example:
      title: Bad Request
      status: 400
      detail: Bad request
