openapi: 3.0.3
info:
  title: Code4Teens REST API
  version: 1.0.0
servers:
- url: /api/v1
paths:
  /users:
    get:
      tags:
      - User
      summary: Returns all users
      operationId: user.get_all
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserBots'
    post:
      tags:
      - User
      summary: Creates user
      operationId: user.create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NaiveUser'
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        409:
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: Conflict
                code: 409
                message: User 123456123456123456 already exists
  /users/{id}:
    get:
      tags:
      - User
      summary: Returns user
      operationId: user.get_one
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserBots'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: Not Found
                code: 404
                message: User 123456123456123456 not found
    put:
      tags:
      - User
      summary: Updates user
      operationId: user.update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartialUser'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: Not Found
                code: 404
                message: User 123456123456123456 not found
    delete:
      tags:
      - User
      summary: Deletes user
      operationId: user.delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: OK
                code: 200
                message: User 123456123456123456 deleted
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: Not Found
                code: 404
                message: User 123456123456123456 not found
  /users/{id}/password:
    put:
      tags:
      - User
      summary: Updates user password
      operationId: user.update_password
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
            example:
              password: new_password
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: OK
                code: 200
                message: Updated password for user 123456123456123456
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: Not Found
                code: 404
                message: User 123456123456123456 not found
  /bots:
    get:
      tags:
      - Bot
      summary: Returns all bots
      operationId: bot.get_all
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bot'
    post:
      tags:
      - Bot
      summary: Creates bot
      operationId: bot.create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                discriminator:
                  type: string
                display_name:
                  type: string
                user_id:
                  type: integer
                msg_id:
                  type: integer
        required: true
      responses:
        201:
          description: Success!
          content:
            application/json:
              schema:
                type: object
  /bots/{id}:
    get:
      tags:
      - Bot
      summary: Returns bot
      operationId: bot.get_one
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Success!
          content:
            application/json:
              schema:
                type: object
    put:
      tags:
      - Bot
      summary: Updates bot
      operationId: bot.update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                discriminator:
                  type: string
                display_name:
                  type: string
                user_id:
                  type: integer
                msg_id:
                  type: integer
        required: false
      responses:
        200:
          description: Success!
          content:
            application/json:
              schema:
                type: object
    delete:
      tags:
      - Bot
      summary: Deletes bot
      operationId: bot.delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Success!
          content: {}
components:
  schemas:
    PartialUser:
      type: object
      properties:
        name:
          type: string
          example: johndoe
        discriminator:
          type: string
          example: '4242'
        display_name:
          type: string
          example: John Doe
        cohort_id:
          type: integer
          example: 1
        is_admin:
          type: boolean
          example: false
    NaiveUser:
      allOf:
        - $ref: '#/components/schemas/PartialUser'
        - type: object
          properties:
            id:
              type: integer
              example: 123456123456123456
    User:
      allOf:
        - $ref: '#/components/schemas/NaiveUser'
        - type: object
          properties:
            created_at:
              type: string
              example: '2021-04-20T08:42:00'
            last_updated:
              type: string
              example: '2021-04-20T08:42:00'
    UserBots:
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
          properties:
            bots:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                    example: 654321654321654321
    PartialBot:
      type: object
      properties:
        name:
          type: string
          example: clockwork
        discriminator:
          type: string
          example: '2121'
        display_name:
          type: string
          example: Clockwork the Bot
        user_id:
          type: integer
          example: 123456123456123456
        msg_id:
          type: integer
          example: 456123456123456123
    NaiveBot:
      allOf:
        - $ref: '#/components/schemas/PartialBot'
        - type: object
          properties:
            id:
              type: integer
              example: 654321654321654321
    Bot:
      allOf:
        - $ref: '#/components/schemas/NaiveBot'
        - type: object
          properties:
            created_at:
              type: string
              example: '2021-04-20T08:42:00'
            last_updated:
              type: string
              example: '2021-04-20T08:42:00'
    Response:
      properties:
        status:
          type: string
        code:
          type: integer
        message:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
# security:
#   - bearerAuth: []
